
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        run: docker build . --file Dockerfile --tag blockTest:$(date +%s)
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: contensis/block-push@v1
        with:
          block-id: blockstest
          alias: chesheast
          project-id: website
          client-id: ${{ secrets.CLIENT_ID }}
          shared-secret: ${{ secrets.SHARED_SECRET }}
