

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

      - uses: contensis/block-push@v1
        with:
          block-id: blockstest
          alias: chesheast
          project-id: website
          client-id: ${{ secrets.CLIENT_ID }}
          shared-secret: ${{ secrets.SHARED_SECRET }}
