name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        USER: ${{ secrets.DOCKER_USER }}
        PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        docker login -u $USER -p $PASS
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag antiloquax/blockstest:latest
    - name: Docker push
      run: docker push antiloquax/blockstest:latest
      
  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Contensis block push action
      uses: contensis/block-push@v1
      with:
        block-id: blockstest
        alias: chesheast
        project-id: website
        auto-release: true
        image-uri: antiloquax/blockstest
        client-id: ${{ secrets.CLIENT_ID }}
        shared-secret: ${{ secrets.SHARED_SECRET }}
        git-token: ${{ secrets.GIT_TOKEN }}
   

